#!/usr/bin/env node
// Generate the compiled version constant from package metadata before building.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const dir = dirname(fileURLToPath(import.meta.url));
const { version } = JSON.parse(readFileSync(join(dir, "package.json"), "utf-8"));
writeFileSync(
  join(dir, "src", "version.ts"),
  `// Auto-generated by generate-version.mjs — do not edit\nexport const VERSION = ${JSON.stringify(version)};\n`,
);
console.log(`version: ${version}`);
