#!/usr/bin/env node
// Reads version from package.json and writes src/version.ts.
// Runs as a prebuild step so the compiled output and bun binary
// both get the version as a plain string constant — no JSON import needed.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const dir = dirname(fileURLToPath(import.meta.url));
const { version } = JSON.parse(readFileSync(join(dir, "package.json"), "utf-8"));
writeFileSync(join(dir, "src", "version.ts"), `// Auto-generated by generate-version.mjs — do not edit\nexport const VERSION = "${version}";\n`);
console.log(`version: ${version}`);
